- hosts: web
  remote_user: ansible
  become: yes
  become_method: sudo
  
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:  
  - name: installing docker-py
    pip:
      name: docker-py
      state: present
      executable: pip3

  - name: running image
    docker_container:
      name: webapp
      image: badboy1/repo:docker
      state: started
      ports:
      - 9000:8080

      
